"""empty message

Revision ID: bd330ba94581
Revises: e820f2bb8f4a
Create Date: 2023-11-28 04:05:18.518279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd330ba94581'
down_revision = 'e820f2bb8f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredientes', schema=None) as batch_op:
        batch_op.drop_constraint('ingredientes_categoria_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredientes', schema=None) as batch_op:
        batch_op.create_unique_constraint('ingredientes_categoria_key', ['categoria'])

    # ### end Alembic commands ###
